# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PestTech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  #Pods for PestTech
    pod 'AlamofireImage'
    pod 'Parse'
    pod 'MessageInputBar'

  # Pods for PestTech

  target 'PestTechTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PestTechUITests' do
    # Pods for testing
  end

end
